services:
  # PHP-FPM (Laravel)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: abitus/php
    container_name: abitus_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www:delegated
    networks:
      - app-network
    depends_on:
      - db
      - redis
      - minio

  # Nginx
  nginx:
    image: nginx:alpine
    container_name: abitus_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8888:80"
      - "8443:443"
    volumes:
      - ./:/var/www:delegated
      - ./entrypoint.sh:/entrypoint.sh
    depends_on:
      - app
    command: ["/bin/sh", "/entrypoint.sh"]
    networks:
      - app-network

  # POSTGRESQL (PostgreSQL)
  db:
    image: postgres:latest
    container_name: abitus_db
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: db_abitus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'abitus_12345678'
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - app-network

  # Redis
  redis:
    image: redis:latest
    container_name: abitus_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - app-network

  # Minio
  minio:
    image: minio/minio
    container_name: abitus_minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniostorage
    ports:
      - "9000:9000"
      - "9091:9091"
    command: server --console-address ":9091" /data
    volumes:
      - minio-data:/data
    networks:
      - app-network

# Networks
networks:
  app-network:
    driver: bridge

# Volumes
volumes:
  dbdata:
    driver: local
  redis-data:
    driver: local
  minio-data:
    driver: local